### ISSUE TITLE
Introduce Buffered Uploads?

### ISSUE THREAD

**Issue by neilabdev** [bertramdev/karman-core#20]
Thanks for the great work, I've been using this API/plugin for some time, and just realized that it may require that whatever is uploaded reside in memory first. Example, if you upload an 7MB image, it will invoke either *CloadFile.setText* or *CloadFile.setBytes*, both of which remain resident in memory, as apposed to to say, if available, *CloadFile.setInputstream* or *CloadFile.setFile*, which could instead be buffered, etc. There is a setInputStream, but from looking at the code, its not intended to be used like:

```java
 CloudFile cloudFile = new CloudFile(provider: provider, parent: directory , name: name)
cloudFile.file = new File("/path/to/file")
// or
cloudFile.inputStream =  new File("/path/to/file").newDataInputStream()
couldFile.save()
```

But instead per doc, only:
 
https://bertramdev.github.io/karman-core/
```java
 CloudFile file = new CloudFile(provider: provider, parent: directory , name: name)

 file.text = "Setting test Content" // file.bytes = "Settings test Content".bytes
 file.contentType = "text/plain"
 if(!file.exists()) {
     file.save()
 }
 
```

Not an issue yet, but for uploading large files, such as video, that could be an issue. Am I overlooking anything? I suppose I can implement my own provider, which I've done before, for the purposes of allowing buffered saves... but it would be specific to my implementation, as apposed to the underlying CloudFile which effects all providers and could benifit everyone. Perhaps I'm mistaken, just thought I'd be sure. Thanks!

**Comment by davydotcom** [comment]
We use this library for 40Gig virtual image upload storage using the stream api. Ensure that when passing an input stream you also must set the content length so 

setInputStream(blah)
setContentLength(23445)
save

Most cloud providers require the content length be know before the upload streams

**Comment by neilabdev** [comment]
Thanks @davydotcom , worked like a charm!

**Comment by davydotcom** [comment]
you reminded me i really need to work on docs for karman. it has a TON of little nuggets in there.

**Comment by neilabdev** [comment]
Yup, I understand entirely. There are useful API's I haven't published because I haven't written documentation yet, in addition to those I have which need updated documentation for new features. As you know, coders are always busy :) But do consider a setFile method, which may be left out because it may vary by provider implementation, etc. But if you think the following would reasonably work, below is a snippet of what is working for me... and with it, documentation wouldn't be necessary as it would be assumed, etc. However, this solution as provide was simple enough once you provided the details, so not having a function works to. Regardless, thanks!

```groovy
abstract class CloudFile implements CloudFileInterface {
    CloudFile setFile(File file) {
        this.setContentLength(file.size())
        this.inputStream = file.newDataInputStream()
        return this
    }
}
```

**Comment by davydotcom** [comment]
Tip don’t use DataInputStream as that has other connotations... you simply want newInputStream()

**Comment by neilabdev** [comment]
Big thanks! I looked at the definition for both  before using and it wasn't clear. Historically in other languages/platforms, different readers could consider how newlines are processed if at all, and thought maybe certain implementations would care while others wouldn't. Therefore assumed *dataInputStream* would be the way to go if you never wanted to alter the data, but guess not. You have saved me some debugging :)
