### ISSUE TITLE
 AzureFile.groovy - Signed Int Limits File Sizes to < 2^31 bytes 

### ISSUE THREAD

**Issue by ntctwfreise** [bertramdev/karman-core#24]
This issue was addressed in AzurePageBlobFile.groovy about 6 months ago, but it also exists in  AzureFile.groovy. (see https://github.com/bertramdev/karman-core/commit/660715031547412c0513c0cd023fd9acdbf8d957#diff-a9b5f5fcba414aafecbe675546dc44eba3a906b5538d3770c772c45e43040f16)

**Comment by davydotcom** [comment]
Resolved
