### ISSUE TITLE
Support Instance Profile Credentials for S3 Provider

### ISSUE THREAD

**Issue by joemccall86** [bertramdev/karman-core#9]
We're looking to replace our custom solution with karman, but the current plugin seems to require IAM credentials in code. AWS supports reading the credentials from the instance profile associated with the EC2 instance.

Basically if you use an instance of `DefaultAWSCredentialsProviderChain` as the `AWSCredentialsProvider` it will support credentials from the following locations:

* Environment Variables
* System Properties
* `~/.aws/credentials`
* Instance Profile of the launched EC2 instance

Logging it here as a bug, but I'll be filing a PR for this as well. I plan to keep the existing strategy, and use the `DefaultAWSCredentialsProviderChain` as a fall-back option when the credentials are not found in code.

**Comment by davydotcom** [comment]
A PR for this would be most welcome thanks!

**Comment by joemccall86** [comment]
I think this issue can be closed.
